# Generated by Django 4.1.2 on 2022-10-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_thistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='thistory',
        ),
    ]
