# Generated by Django 4.1.2 on 2022-10-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_history_delete_thistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='id',
            new_name='qid',
        ),
    ]
